import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import ts from 'typescript';
import assert from 'node:assert/strict';
const cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));const exports={};cache.set(file,exports);vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText,{exports,require:p=>load(path.resolve(path.dirname(file),p.endsWith('.json')?p:p+'.ts')),Date,Set,Math});return exports;}
const {firstTask,topics,recommend,foundationNext,skill}=load('lib/training.ts');
const {coreUnits,coreProgress,nextCoreTask}=load('lib/core-course.ts');
const now=Date.now(),day=86400000,unit=coreUnits[0];
const win=(task,offset=0,extra={})=>({id:task+offset,task,session:task+offset,kind:'run',passed:true,hints:0,time:now+offset,elapsed:30,before:0,mode:'Practice',...extra});
assert.equal(firstTask.id,'core-values-complete');assert.equal(topics[0],'Python core');
assert.equal(recommend([],'Practice').task.id,firstTask.id);
assert.equal(recommend([win(firstTask.id)],'Practice').task.id,'core-values-write');
assert.equal(recommend([],'Practice','Все темы',firstTask.id).task.id,'core-values-write');
assert.equal(recommend([],'Practice','Collections').task.topic,'Collections');
assert.equal(recommend([],'Production').task.production,true);
assert.equal(coreProgress(unit,[],now).status,'upcoming');
const written=[win(firstTask.id,0,{kind:'theory',score:100})];
assert.equal(coreProgress(unit,written,now).status,'learning');assert.equal(coreProgress(unit,written,now).solved,0);
assert.equal(coreProgress(unit,[win(firstTask.id,0,{hints:1})],now).solved,0);
assert.equal(coreProgress(unit,[win(firstTask.id),win(firstTask.id,1,{kind:'hint',session:firstTask.id+0})],now).solved,0);
const solved=unit.taskIds.map((id,i)=>win(id,i));
assert.equal(coreProgress(unit,solved,now+10).status,'learning');
assert.equal(coreProgress(unit,solved,now+10).due,false);
assert.equal(coreProgress(unit,[...solved,win(unit.taskIds[2],100)],now+100).status,'learning');
assert.equal(coreProgress(unit,[...solved,win(unit.taskIds[2],day+2,{session:solved[2].session})],now+day+2).status,'learning');
assert.equal(coreProgress(unit,[...solved,win(unit.taskIds[2],day+2)],now+day+2).status,'mastered');
assert.equal(coreProgress(unit,solved,now+day+2).due,true);
assert.equal(nextCoreTask(solved,'',now+day+2).id,unit.taskIds[2]);
assert.equal(skill('Python core',written).mastery,0);
assert.equal(skill('Python core',solved).proven,false);
assert.equal(skill('Python core',[win(firstTask.id)]).calibrationError,0);
const all=coreUnits.flatMap(u=>u.taskIds.map((id,i)=>win(id,i)));
assert.equal(nextCoreTask(all,'',now+10),null);
const mastered=[...all,...coreUnits.map(u=>win(u.taskIds[2],day+3))];
assert.equal(skill('Python core',mastered).proven,true);
assert.equal(skill('Python core',mastered).mastery,100);
console.log('PASS: core order, manual modes, written evidence, hints, 24h threshold, distinct sessions, due review and full-module mastery.');
