import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import assert from 'node:assert/strict';
const exports={};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/training.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText,{exports,require:p=>JSON.parse(fs.readFileSync('lib/'+p)),Date,Set,Math});
const {firstTask,topics,recommend,foundationNext,skill}=exports;
const win=(task,hints=0)=>({id:task,task,session:task,kind:'run',passed:true,hints,time:Date.now(),elapsed:30,before:0,mode:'Practice'});
assert.equal(firstTask.id,'foundation-greeting');
assert.equal(topics[0],'Python core');
assert.equal(recommend([],'Practice').task.id,firstTask.id);
assert.equal(recommend([win(firstTask.id)],'Practice').task.id,'foundation-even');
assert.equal(recommend([win(firstTask.id),win('foundation-even')],'Practice').task.id,'foundation-sum-positive');
assert.equal(foundationNext([win(firstTask.id,1)]),firstTask.id,'assisted success does not certify independence');
assert.equal(recommend([],'Practice','Все темы',firstTask.id).task.id,'foundation-even','skipping stays in foundation route');
assert.equal(recommend([],'Practice','Collections').task.topic,'Collections','manual choice remains available');
assert.equal(recommend([],'Production').task.production,true);
assert.equal(foundationNext([win(firstTask.id),win('foundation-even'),win('foundation-sum-positive')]),undefined);
assert.equal(skill('Python core',[win(firstTask.id)]).calibrationError,0,'missing confidence is not a wrong prediction');
console.log('PASS: first session, core sequence, assistance, skip, manual topic, production and optional confidence.');
