"use client";
import {useState} from 'react';
import {ArrowRight,BookOpen,PenLine,RotateCcw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {theory} from '@/lib/theory';
import {assessKnowledge,knowledgeChecks,type KnowledgeCheck} from '@/lib/knowledge';
import {tasks,type Entry} from '@/lib/training';
type Props={entries:Entry[];onSubmit:(check:KnowledgeCheck,answer:string,score:number)=>void;onApply:(topic:string)=>void};
export function TheoryPanel({entries,onSubmit,onApply}:Props){
 const topics=Object.keys(theory);const [topic,setTopic]=useState(topics[0]);const [answer,setAnswer]=useState('');const [assessment,setAssessment]=useState<ReturnType<typeof assessKnowledge>|null>(null);
 const check=knowledgeChecks.find(item=>item.topic===topic)||knowledgeChecks[0];const currentTheory=theory[topic];const theoryTaskId=tasks.find(item=>item.topic===topic)?.id;const completed=entries.filter(item=>item.kind==='theory'&&item.task===theoryTaskId).length;
 const selectTopic=(next:string)=>{setTopic(next);setAnswer('');setAssessment(null)};
 const submit=()=>{if(answer.trim().length<20)return;const result=assessKnowledge(check,answer);setAssessment(result);onSubmit(check,answer,result.score)};
 return <div className="theory-shell"><aside className="theorynav"><div className="theorynav-label"><BookOpen size={15}/> Учебные блоки</div>{topics.map(item=><button key={item} className={item===topic?'selected':''} onClick={()=>selectTopic(item)}>{item}<ArrowRight size={14}/></button>)}</aside><article className="theoryarticle"><div className="theoryarticle-top"><span className="pill">С нуля · теория</span><span className="theoryprogress">{topics.indexOf(topic)+1} / {topics.length} · {completed?'Проверено':'Не проверено'}</span></div><h1>{currentTheory.title}</h1><p className="theorylead">Сначала соберите mental model, затем объясните её своими словами и примените в задаче.</p><ol>{currentTheory.points.map((point,index)=><li key={index}>{point}</li>)}</ol><section className="knowledge-check"><div className="knowledge-check-title"><span><PenLine size={17}/> Письменная проверка</span><small>Без вариантов ответа</small></div><h2>{check.title}</h2><p>{check.prompt}</p><textarea value={answer} onChange={event=>{setAnswer(event.target.value);setAssessment(null)}} placeholder={check.placeholder} rows={7} aria-label="Письменный ответ"/><div className="knowledge-actions"><span>{answer.trim().length}/20 символов минимум</span><Button onClick={submit} disabled={answer.trim().length<20}>Проверить объяснение</Button></div>{assessment&&<div className={'knowledge-result '+(assessment.score>=60?'good':'needs-work')}><div className="knowledge-score"><b>{assessment.score}%</b><span>{assessment.score>=80?'Механизм объяснён уверенно':assessment.score>=60?'Есть рабочее понимание':'Нужно разобрать тему ещё раз'}</span></div>{assessment.missing.length>0&&<p><b>Не хватает:</b> {assessment.missing.map(item=>item.label).join(' · ')}</p>}<p><b>Эталон для сверки:</b> {check.reference}</p><button className="knowledge-reset" onClick={()=>{setAnswer('');setAssessment(null)}}><RotateCcw size={14}/> Попробовать ещё раз</button></div>}</section><div className="theory-apply"><div><b>Закрепить в коде</b><p>После объяснения решите короткую задачу по этой теме. Готовое решение заранее не показывается.</p></div><Button variant="outline" onClick={()=>onApply(topic)}>Открыть задачу <ArrowRight size={15}/></Button></div></article></div>;
}
