export type KnowledgeConcept={label:string;terms:string[]};
export type KnowledgeCheck={id:string;topic:string;title:string;prompt:string;placeholder:string;concepts:KnowledgeConcept[];reference:string};
export const knowledgeChecks:KnowledgeCheck[]=[
 {id:'k-python-core',topic:'Python core',title:'Переменные и объекты',prompt:'Объясните: что хранит переменная в Python, чем отличаются == и is, и почему if value может пропустить допустимое значение?',placeholder:'Напишите объяснение с примером.',concepts:[{label:'ссылка на объект',terms:['ссылка','объект','reference']},{label:'равенство значений',terms:['==','значени']},{label:'идентичность',terms:[' is ','идентич','identity']},{label:'ложность 0/None/пустых',terms:['none','0','пуст','ложн']}],reference:'Имя связано с объектом. == сравнивает значения, is — идентичность. 0, None и пустые контейнеры ложны.'},
 {id:'k-collections',topic:'Collections',title:'Выбор коллекции',prompt:'Сравните list, set и dict. Для каждой структуры назовите главное свойство и подходящую операцию.',placeholder:'Опишите три структуры и backend-пример.',concepts:[{label:'list хранит порядок',terms:['list','список','поряд']},{label:'set уникален',terms:['set','множест','уник']},{label:'dict ключ-значение',terms:['dict','словар','ключ']},{label:'хеширование/сложность',terms:['o(1)','хеш','membership']}],reference:'list хранит порядок и дубли, set — уникальные хешируемые элементы, dict — связь ключ-значение.'},
 {id:'k-functions',topic:'Functions',title:'Контракт функции',prompt:'Что входит в контракт функции? Объясните опасность изменяемого аргумента по умолчанию и способ упростить тестирование.',placeholder:'Ответьте через вход, выход, ошибки и эффекты.',concepts:[{label:'вход и выход',terms:['вход','выход','аргумент','возврат']},{label:'ошибки',terms:['ошиб','исключ']},{label:'побочные эффекты',terms:['побоч','состояни','side effect']},{label:'mutable default',terms:['по умолчанию','default','none','изменяем']}],reference:'Контракт описывает вход, результат, ошибки и побочные эффекты. Для mutable default безопаснее использовать None.'},
 {id:'k-exceptions',topic:'Exceptions',title:'Граница ошибки',prompt:'Объясните разницу между TypeError и ValueError. Где должна находиться граница try/except и зачем нужно raise ... from ...?',placeholder:'Разберите ошибку валидации входа.',concepts:[{label:'TypeError',terms:['typeerror','тип']},{label:'ValueError',terms:['valueerror','значени']},{label:'узкий try',terms:['узк','конкрет','try']},{label:'цепочка причин',terms:['from','цепоч','причин']}],reference:'TypeError — неподходящий тип, ValueError — неподходящее значение. Ловите узкую операцию и сохраняйте причину через from.'},
 {id:'k-external',topic:'External failures',title:'Timeout и повтор',prompt:'Сервис вернул timeout после POST. Что могло произойти и какие условия нужны для безопасного retry?',placeholder:'Опишите неопределённый результат и защиту от дублей.',concepts:[{label:'результат неизвестен',terms:['неизвест','выполнил','timeout']},{label:'временная ошибка',terms:['временн','retry','повтор']},{label:'идемпотентность',terms:['идемпотент','idempotency']},{label:'backoff/лимит',terms:['backoff','лимит','jitter']}],reference:'Timeout не доказывает, что операция не выполнена. Нужны идемпотентный ключ, лимит и backoff.'},
 {id:'k-oop',topic:'OOP',title:'Инвариант объекта',prompt:'Что такое инвариант объекта? Приведите пример для ограниченного кэша и объясните ценность композиции.',placeholder:'Назовите правило, которое нельзя нарушить.',concepts:[{label:'инвариант',terms:['инвариант','правил']},{label:'состояние экземпляра',terms:['self','экземпляр','состояни']},{label:'capacity',terms:['capacity','лимит','размер']},{label:'композиция',terms:['композиц','зависим']}],reference:'Инвариант истинен после каждого публичного метода. Для кэша len(cache) <= capacity.'},
 {id:'k-iterators',topic:'Iterators / generators',title:'Ленивый поток',prompt:'Чем iterable отличается от iterator и generator? Почему генератор удобен для большого файла и одноразов?',placeholder:'Свяжите yield, next и память.',concepts:[{label:'iterable/iterator',terms:['iterable','итерируем','iterator','итератор']},{label:'yield',terms:['yield']},{label:'ленивость',terms:['ленив','lazy']},{label:'одноразовое состояние',terms:['однораз','исчерп','next']}],reference:'Generator — ленивый iterator с yield: он хранит состояние и выдаёт значения по запросу.'},
 {id:'k-decorators',topic:'Decorators',title:'Обёртка функции',prompt:'Что делает декоратор? Объясните роль functools.wraps и риск состояния в замыкании.',placeholder:'Опишите порядок вызова wrapper и функции.',concepts:[{label:'функция принимает функцию',terms:['принима','функц','вызыва']},{label:'wrapper',terms:['обёртк','wrapper']},{label:'wraps',terms:['wraps','__wrapped__']},{label:'состояние',terms:['состояни','кэш','между выз']}],reference:'Декоратор получает функцию и возвращает wrapper. wraps сохраняет имя и метаданные.'},
 {id:'k-typing',topic:'Typing',title:'Аннотация не валидация',prompt:'Что гарантирует аннотация типа, а чего не гарантирует во время выполнения? Где проверять HTTP-ввод?',placeholder:'Сравните static checking и runtime validation.',concepts:[{label:'статический анализ',terms:['статичес','анализ','mypy','type checker']},{label:'не runtime запрет',terms:['не гарант','runtime','выполн']},{label:'граница ввода',terms:['границ','http','вход']},{label:'валидация',terms:['валид','провер']}],reference:'Аннотации помогают анализатору, но сами не запрещают неправильные значения. Ввод валидируется на границе.'},
 {id:'k-async',topic:'Async',title:'Event loop и блокировка',prompt:'Почему async def сам по себе не делает код быстрым? Что случится с блокирующим клиентом внутри endpoint?',placeholder:'Объясните await и event loop.',concepts:[{label:'await',terms:['await','управлен','корутин']},{label:'конкурентность',terms:['конкурент','gather','taskgroup']},{label:'блокировка loop',terms:['блокир','event loop','синхрон']},{label:'async client/thread',terms:['async-клиент','поток','thread','процесс']}],reference:'await отдаёт управление только во время неблокирующего ожидания. Синхронный I/O блокирует event loop.'},
 {id:'k-testing',topic:'Testing',title:'Тест как защита контракта',prompt:'Какие три категории входов нужно проверить? Почему fake внешнего сервиса лучше реального HTTP в unit-тесте?',placeholder:'Опишите обычный, граничный и ошибочный сценарии.',concepts:[{label:'обычный сценарий',terms:['обычн','happy']},{label:'граница',terms:['гранич','edge']},{label:'ошибка',terms:['ошиб','исключ']},{label:'fake/детерминизм',terms:['fake','заглуш','детермин','сеть']}],reference:'Проверяйте обычный, граничный и ошибочный сценарии. Fake делает внешние сбои воспроизводимыми.'},
 {id:'k-http',topic:'HTTP / FastAPI',title:'Граница HTTP и сервиса',prompt:'Где должна находиться бизнес-проверка, нужная HTTP endpoint и фоновой задаче? Что проверяет integration-тест?',placeholder:'Разделите route, service и repository.',concepts:[{label:'HTTP-контракт',terms:['метод','статус','контракт','endpoint']},{label:'service',terms:['service','бизнес','правил']},{label:'repository',terms:['repository','данн','база']},{label:'integration',terms:['интеграц','asgi','тест']}],reference:'Route отвечает за транспорт, service — за правила, repository — за данные. Integration проверяет их связку.'},
 {id:'k-sql',topic:'PostgreSQL / SQL',title:'SQL: строки и группы',prompt:'Объясните порядок WHERE, GROUP BY и HAVING. Почему LEFT JOIN может превратиться в INNER JOIN?',placeholder:'Ответьте на примере пользователей и заказов.',concepts:[{label:'WHERE до группировки',terms:['where','до групп']},{label:'HAVING после группировки',terms:['having','после групп']},{label:'LEFT JOIN сохраняет левую сторону',terms:['left join','сохраня']},{label:'условие убирает NULL',terms:['null','where','inner']}],reference:'WHERE фильтрует строки до GROUP BY, HAVING — группы после него. Условие по правой таблице в WHERE удаляет NULL-строки.'}
];
export function assessKnowledge(check:KnowledgeCheck,answer:string){const text=answer.toLowerCase();const matched=check.concepts.filter(concept=>concept.terms.some(term=>text.includes(term.toLowerCase())));const score=answer.trim().length<40?Math.min(45,Math.round(matched.length/check.concepts.length*100)):Math.round(matched.length/check.concepts.length*100);return {score,matched,missing:check.concepts.filter(concept=>!matched.includes(concept))};}
